### ISSUE TITLE
nodejs see restart service

### ISSUE THREAD

**Issue by mikkoyli** [awareframework/sensedash#36]
Mysql errors should be handled properly and nodejs should restart on errors

**Comment by mikkoyli** [comment]
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    | Unhandled rejection Error: ER_DATA_TOO_LONG: Data too long for column 'data' at row 1
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at Query.Sequence._packetToError (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at Query.ErrorPacket (/usr/src/app/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at Protocol._parsePacket (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:279:23)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at Parser.write (/usr/src/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at Protocol.write (/usr/src/app/node_modules/mysql/lib/protocol/Protocol.js:39:16)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at TLSSocket.ondata (_stream_readable.js:639:20)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at emitOne (events.js:116:13)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at TLSSocket.emit (events.js:211:7)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at addChunk (_stream_readable.js:263:12)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at readableAddChunk (_stream_readable.js:250:11)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at TLSSocket.Readable.push (_stream_readable.js:208:10)
upbeat_brahmagupta.3.vbkhnjoxgpsx@ip-172-31-24-249    |     at TLSWrap.onread (net.js:607:20)
