### ISSUE TITLE
server crashes on missing timestamp

### ISSUE THREAD

**Issue by mikkoyli** [awareframework/sensedash#37]
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    | TypeError: Cannot read property 'timestamp' of undefined
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at sensorController.addData (/usr/src/app/controllers/sensorController.js:51:20)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
compassionate_jepsen.1.wh7qnykilf72@ip-172-31-29-54    |     at jsonParser (/usr/src/app/node_modules/body-parser/lib/types/json.js:118:7

**Comment by mikkoyli** [comment]
fixed
