### ISSUE TITLE
Fix database timeout error

### ISSUE THREAD

**Issue by mikkoyli** [awareframework/sensedash#46]
(node:2014) UnhandledPromiseRejectionWarning: TypeError: res.error is not a function
    at handleInsert (/home/ubuntu/sensedash-stress/controllers/sensorController.js:64:9)
    at <anonymous>
(node:2014) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2014) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2019) UnhandledPromiseRejectionWarning: TypeError: res.error is not a function
    at handleInsert (/home/ubuntu/sensedash-stress/controllers/sensorController.js:64:9)
    at <anonymous>
(node:2019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mikkoyli** [comment]
fixed
